#!/usr/bin/env python3
"""Write a per-rule, JSON-backed audit for the optional RE2 engine."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import cast


ROOT = Path(__file__).resolve().parents[1]
sys.path[:0] = [str(ROOT / "src"), str(ROOT / "tests")]

from agentsweep.scanner import ENGINE_INVENTORY, ENGINE_SUMMARY  # noqa: E402
from test_regex_engine_parity import ALL_FIXTURES  # noqa: E402


def _reason_category(reason: str | None) -> str:
    if reason is None:
        return "re2-compatible"
    if "(?<!" in reason:
        return "lookbehind"
    if "(?=" in reason or "(?!" in reason:
        return "lookaround"
    if "\\Z" in reason:
        return "python-only-anchor"
    if "character-class" in reason:
        return "unicode-character-class"
    if "case-folding" in reason:
        return "unicode-case-folding"
    if "not installed" in reason:
        return "optional-dependency-unavailable"
    if "forced" in reason:
        return "forced-stdlib"
    return "other"


def _audit() -> dict[str, object]:
    rules = []
    for entry in ENGINE_INVENTORY:
        copied = dict(entry)
        copied["reason_category"] = _reason_category(cast(str | None, entry["fallback_reason"]))
        fixture_exists = entry["rule_id"] in ALL_FIXTURES
        copied["fixture_exists"] = fixture_exists
        copied["parity_status"] = (
            "covered by tests/test_regex_engine_parity.py"
            if fixture_exists
            else "missing synthetic fixture"
        )
        rules.append(copied)
    return {"summary": ENGINE_SUMMARY, "rules": rules}


def _markdown(audit: dict[str, object]) -> str:
    summary = audit["summary"]
    rules = audit["rules"]
    assert isinstance(summary, dict)
    assert isinstance(rules, list)
    fixture_count = sum(bool(rule["fixture_exists"]) for rule in rules if isinstance(rule, dict))
    fallback_categories: dict[str, int] = {}
    for rule in rules:
        assert isinstance(rule, dict)
        category = str(rule["reason_category"])
        fallback_categories[category] = fallback_categories.get(category, 0) + 1

    lines = [
        "# RE2 compatibility audit",
        "",
        "Generated by `scripts/audit_re2_compatibility.py` from the live rule registry.",
        "The machine-readable audit, including every original pattern, is",
        "[`artifacts/re2_compatibility.json`](../artifacts/re2_compatibility.json).",
        "",
        f"- Requested engine: `{summary['requested_engine']}`",
        f"- Effective engine: `{summary['effective_engine_mode']}`",
        f"- RE2 available: `{summary['re2_available']}` ({summary['re2_version']})",
        f"- Rules: {summary['re2_rule_count']} RE2, {summary['stdlib_rule_count']} stdlib",
        "- Unicode-guarded RE2 rules use stdlib only for non-ASCII text, preserving Python ``re`` semantics.",
        f"- RE2 uses exact stdlib iteration below {summary['short_input_fallback_chars']} characters or after {summary['dense_match_fallback_limit']} matches for one rule; registry selection remains static.",
        f"- Synthetic fixture coverage: {fixture_count}/{len(rules)} rules; covered fixtures participate in full-finding parity tests.",
        "",
        "## Selection categories",
        "",
        "| Category | Rules |",
        "|---|---:|",
    ]
    lines.extend(f"| {category} | {count} |" for category, count in sorted(fallback_categories.items()))
    lines.extend([
        "",
        "## Per-rule selection",
        "",
        "| Rule | Backend | RE2 compile | Boundary guard | Unicode guard | Guard reason | Fallback reason |",
        "|---|---|---|---|---|---|---|",
    ])
    for rule in rules:
        assert isinstance(rule, dict)
        reason = str(rule["fallback_reason"] or "—").replace("|", "\\|")
        lines.append(
            "| {rule_id} | {selected_backend} | {compile_status} | {semantic_guard} | {unicode_guard} | {guard_reason} | {reason} |".format(
                rule_id=rule["rule_id"],
                selected_backend=rule["selected_backend"],
                compile_status=rule["compile_status"],
                semantic_guard=rule["semantic_guard"],
                unicode_guard=rule["unicode_guard"],
                guard_reason=str(rule["guard_reason"] or "—").replace("|", "\\|"),
                reason=reason,
            )
        )
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--json", type=Path, default=ROOT / "artifacts/re2_compatibility.json")
    parser.add_argument("--markdown", type=Path, default=ROOT / "docs/RE2_COMPATIBILITY.md")
    args = parser.parse_args()

    audit = _audit()
    args.json.parent.mkdir(parents=True, exist_ok=True)
    args.json.write_text(json.dumps(audit, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    args.markdown.parent.mkdir(parents=True, exist_ok=True)
    args.markdown.write_text(_markdown(audit), encoding="utf-8")
    print(f"wrote {args.json}")
    print(f"wrote {args.markdown}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
